[package]
name = "spotty"
version = "0.8.2"
authors = ["Michael Herger <michael@herger.net>"]

[[bin]]
name = "spotty"
path = "src/main.rs"
doc = false

[dependencies]
env_logger = "0.4.0"
futures = "0.1.8"
getopts = "0.2.14"
log = "0.3.5"
tokio-core = "0.1.2"
tokio-signal = "0.1.2"

[dependencies.librespot]
git = "https://github.com/michaelherger/librespot.git"
branch = "refactor-0817"
#path = "../librespot"
default-features = false
# enable the following for macOS <= 10.9 compatibility
#features = ["with-tremor","with-lewton"]

[profile.release]
lto = true
panic = 'abort'
