[package]
name = "spotty"
version = "0.9.3"
authors = ["Michael Herger <michael@herger.net>"]

[[bin]]
name = "spotty"
path = "src/main.rs"
doc = false

[dependencies]
env_logger = "0.4.0"
rust-crypto = "0.2.36"
futures = "0.1.8"
getopts = "0.2.14"
log = "0.3.5"
tokio-core = "0.1.2"
tokio-io = "0.1"
tokio-signal = "0.1.2"

[dependencies.librespot]
git = "https://github.com/michaelherger/librespot.git"
branch = "refactor-0817"
#path = "../librespot"
default-features = false
# enable the following for macOS <= 10.9 compatibility
#features = ["with-tremor","with-lewton"]

[replace]
"rust-crypto:0.2.36" = { git = "https://github.com/awmath/rust-crypto.git", branch = "avx2" }

[profile.release]
lto = true
panic = 'abort'
